// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nameutilities.proto

package services;

public final class NameUtilitiesProto {
  private NameUtilitiesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nameutilities_Prefix_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nameutilities_Prefix_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nameutilities_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nameutilities_Name_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023nameutilities.proto\022\rnameutilities\"\030\n\006" +
      "Prefix\022\016\n\006prefix\030\001 \001(\t\"\024\n\004Name\022\014\n\004name\030\001" +
      " \001(\t2P\n\rNameUtilities\022?\n\017GetNameByPrefix" +
      "\022\025.nameutilities.Prefix\032\023.nameutilities." +
      "Name\"\000B \n\010servicesB\022NameUtilitiesProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_nameutilities_Prefix_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nameutilities_Prefix_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nameutilities_Prefix_descriptor,
        new java.lang.String[] { "Prefix", });
    internal_static_nameutilities_Name_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nameutilities_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nameutilities_Name_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
