// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: name_utilities.proto

package services;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nameutilities.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
