// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nameutilities.proto

package services;

public interface PrefixOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nameutilities.Prefix)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string prefix = 1;</code>
   */
  java.lang.String getPrefix();
  /**
   * <code>optional string prefix = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();
}
